[package]
name = "void"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.windows]
version = "0.*"
features = [
    "Win32_Foundation", 
    "Win32_Graphics", 
    "Win32_System_SystemServices", 
    "Win32_UI_WindowsAndMessaging", 
    "Win32_System_Threading", 
    "Win32_UI_Input", 
    "Win32_UI_Input_KeyboardAndMouse", 
    "Win32_System_WindowsProgramming", 
    "Wdk_System_SystemInformation", 
    "Win32_Graphics_Gdi", 
    "Win32_Graphics_OpenGL"
    ]

[dependencies]
lazy_static = "1.4.0"
once_cell = "1.13"
parking_lot = "0.12.1"
rand = "0.8.5"
glu-sys = "0.1.4"
gl = "0.14"
retour = { version = "0.3.1", features = ["static-detour"] }
egui = "0.21.0"
clipboard = "0.5.0"
win_key_codes = "0.1.2"
jni = "0.21.1"
winapi = { version = "0.3.8", features = ["libloaderapi", "consoleapi", "minwindef", "processenv", "winbase", "handleapi", "wingdi", "windef", "winuser"] }
